name: Publish Python 🐍 distribution 📦 to PyPI
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    name: Build and publish distribution 📦 on test-pypi
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/<package-name>
    permissions:
      id-token: write  # mandatory for trusted publishing
    
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install Poetry and build package
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create false
        poetry install --no-interaction
        poetry build

    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1


